#:schema node_modules/@cloudflare/workers-types/experimental/index.d.ts

name = "farmacia-resta"
compatibility_date = "2026-07-15"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Le variabili d'ambiente vanno configurate tramite wrangler secrets o dashboard Cloudflare
[vars]
